#!/usr/bin/env bash
#  This script is displaying "Best School" 10 times
#+ but displays "Hi" at the 9th iteration
i=1
while [ $i -le 10 ]; do
	if [ $i = 9 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
