#!/user/bin/env bash
#  A Bash script that configures an Ubuntu server with the following;
#+ localhost resolves to 127.0.0.2,
#+ facebook.com resolves to 8.8.8.8
cp /etc/hosts /etc/hosts.old
echo -e '127.0.0.2\tlocalhost' > /etc/hosts.old
echo -e '8.8.8.8\tfacebook.com' >> /etc/hosts.old
cp -f /etc/hosts.old /etc/hosts
